---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:8-slim
  commands:
  - npm install --log-level error --registry https://npm.billy.dk
  - npm run lint
  - npm run build
  - npm run test

...